### PR TITLE
give access to raw result

### PR DESCRIPTION
**Pull request by tzemanovic**
I'd like to format the result myself, so I've added a new function `runForm'`, please see the example.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Please rebase against current `add-sub-parsers`.

**Comment by mrkkrp** [comment]
Also: I'd rather avoid having an executable component.

**Comment by mrkkrp** [comment]
Not reviewing until you rebase because it's difficult to tell which changes are new. But I don't see why we can't return normal data structure from `runForm` and let the user convert it to JSON as necessary. Since version 1.0.0 can have breaking changes, why not just change the type of `runForm`.

**Comment by tzemanovic** [comment]
I've rebased and removed the executable.

I like the idea of changing the `runForm` as it provides more flexibility and doesn't require the callback success value to be an instance of `ToJSON`.

I'll also export `toResponse`, which can be used to get the original JSON response value.

**Comment by tzemanovic** [comment]
Since we're changing the API already and because we now expose `BranchState`, can we also rename:

The callback result:
- `FormResult` => `ValidationResult`
- `FormResultError` => `ValidationError`
- `FormResultSuccess` => `ValidationSuccess`

and overall result:
- `BranchState` => `FormResult`
- `ParsingFailed` => `FormParsingError`
- `ValidationFailed` => `FormValidationError`
- `Succeeded` => `FormSuccess`

**Comment by mrkkrp** [comment]
Wow, that's quite a few changes and some of them are unrelated to the branch/PR that you opened this PR against. Some changes seem unnecessary (such as packing `String` as `Text` we get a `String` from Aeson anyway, so I don't see much value in repacking), others need thinking to decide what is best. Let's not rush. I'll merge `add-sub-parsers` branch which adds `subParser` and `value` with your corrections added. And then I think we need to apply one change at a time discussing them one by one.

So let me close this PR for now.

**Comment by mrkkrp** [comment]
If you don't feel like going throw this "one change at a time" workflow, I can pick up the ideas that I like and open PRs myself. I'll add you as a reviewer then.

**Comment by tzemanovic** [comment]
Yup, that sounds good. Cheers!

**Pull request closed without merging**
